development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:4cc0c7abbd1d1efd24ed650756b2a3d5@soapfish.redistogo.com:11339/
  channel_prefix: messageme_production
